apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: app.sample.com
    http:
      paths:
      - path: /
        backend:
          service:
            name: app-green
            port:
              number: 80
        pathType: Prefix  