name: aks-blue-green-appgw

on:
  workflow_dispatch:

env:
  ACR_NAME: pocregostryb3.azurecr.io
  RESOURCE_GROUP: poc-b3-2
  AKS_CLUSTER_NAME: poc-cluster-b3

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: Azure/docker-login@v1
      with:
        login-server: pocregostryb3.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t pocregostryb3.azurecr.io/demo:${{ github.sha }}
        docker push pocregostryb3.azurecr.io/demo:${{ github.sha }}

  deploy:

    runs-on: ubuntu-latest
    needs: build
    environment: deploy    

    steps:
    - uses: actions/checkout@v3

    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "__version__"
        replace: 0.0.6.1
        regex: false    

    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "__image__"
        replace: 'pocregostryb3.azurecr.io/demo:${{ github.sha }}'
        regex: false 

    - name: Set cluster context
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.AKS_CLUSTER_NAME }}
        resource-group: ${{ env.RESOURCE_GROUP }}
    
    # Runs a set of commands using the runners shell
    - uses: Azure/k8s-deploy@v4.5
      with:
        images: 'pocregostryb3.azurecr.io/demo:${{ github.sha }}'
        manifests: |
            deployment-blue.yml
            service.yml
            ingress-blue.yml
        strategy: blue-green
        action: deploy
        route-method: ingress
        force: true
        namespace: blue

  promotereject:
    runs-on: ubuntu-latest
    environment: approvalaks 
    needs: deploy
    steps:
    - uses: actions/checkout@v2

    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "__version__"
        replace: 0.0.6
        regex: false    

    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "__image__"
        replace: 'pocregostryb3.azurecr.io/demo:${{ github.sha }}'
        regex: false 

    - name: Set cluster context
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.AKS_CLUSTER_NAME }}
        resource-group: ${{ env.RESOURCE_GROUP }}

    - name: Promote App
      uses: Azure/k8s-deploy@v4.5
      if: ${{ success() }}
      with:
        namespace: green
        images: 'pocregostryb3.azurecr.io/demo:${{ github.sha }}'
        manifests: |
            deployment-green.yml
            service.yml
            ingress.yml
        strategy: blue-green
        route-method: ingress
        action: promote
        force: true 
        

    - name: Reject App
      uses: azure/k8s-deploy@v4.5
      if: ${{ failure() }}
      with:
        namespace: blue
        images: 'pocregostryb3.azurecr.io/demo:${{ github.sha }}'
        manifests: |
            deployment-blue.yml
            service.yml
            ingress.yml
        strategy: blue-green
        route-method: ingress
        action: reject
        force: true
        